---

- name: RedHat Os vars
  set_fact:
    open_gl_pkgs:
      - mesa-dri-drivers 
      - mesa-libGL
  when: ansible_os_family == "RedHat"

- name: Install OpenGL
  package:
    name: '{{ open_gl_pkgs }}'
    state: present
  become: true

- name: Configure compton with generic/dotfile
  include_role:
    name: generic
    tasks_from: dotfile
  vars:
    package_redhat: "compton"
    package_debian: "compton"
    config_dir: "{{ ansible_env.HOME }}/.config/"
    config_src: "{{ playbook_dir }}/roles/compton/files/compton.conf"
    config_dest: "{{ ansible_env.HOME }}/.config/compton.conf"

- name: Configure i3 to launch compton
  lineinfile:
    path: "{{ i3_config_file }}"
    state: present
    line: exec --no-startup-id compton
