---

- name: Install Dependencies i3
  yum:
    name:
      - libxcb-devel 
      - xcb-util-keysyms-devel 
      - xcb-util-devel 
      - xcb-util-wm-devel 
      - xcb-util-xrm-devel 
      - yajl-devel 
      - libXrandr-devel 
      - startup-notification-devel 
      - libev-devel 
      - xcb-util-cursor-devel 
      - libXinerama-devel 
      - libxkbcommon-devel 
      - libxkbcommon-x11-devel 
      - pcre-devel 
      - pango-devel 
      - gcc 
      - automake 
      - i3status 
      - i3lock
  become: true
