execute pathogen#infect()
syntax on
filetype plugin indent on

" Added settings
set number
set expandtab                       "always add spaces as tabs
set nowrap                          "Dont like wrapin in vim"
set colorcolumn=110                 "Colorcolumn length"
set timeoutlen=1000 ttimeoutlen=0   "Esc delay time"
set incsearch                       "Show search matches while typing"
set wildmenu                        "Tab complete vim command menu"
set t_Co=256                        "Set to 16 to fix pantheon term colors in vim"
set backspace=indent,eol,start      "Set backspace on everything in insert mode, for OS X"
set softtabstop=0
set list                            "list special char's
set listchars=tab:>\                "show tabs as ">"
set ttyfast                         "faster scrolling
colorscheme marvin_martian

" Tab setting for diferent syntax
autocmd FileType tex,latex,vim,markdown,python,sh call TabOther()
autocmd FileType tex,latex,markdown,text call TextSettings()
autocmd FileType c call TabC()

" Settings for markdown
let g:tex_flavor='latex'
function TextSettings()
    set list
    set listchars=tab:▸\ ,eol:~
    set spell spelllang=en_us
endfunction

" Finction for setting tabs for filetypes other than c
function TabOther()
    set tabstop=4
    set shiftwidth=4
endfunction

" Finction for setting tabs for c filetype
function TabC()
    set tabstop=8
    set shiftwidth=8
endfunction

" ctl-R to render latex file
map <C-R> :! pdflatex -interaction=batchmode %<CR>

"Delete line mapings
nnoremap D v$"_d
nnoremap d v$"_d<Esc>O<Esc>
" vertical split key map"
nnoremap \ :vsp<CR>:wincmd l<CR>
imap <C-\> <Esc>:vsp<CR>

" Keymapping for window management
map = <C-W>+
map - <C-W>-
map , :vertical resize +5<CR>
map . :vertical resize -5<CR>
"Unmap p in normal mode because of tmux p command"
map p <Nop> 

" Syntastic recommended settings
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1  
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_mode_map = { 'passive_filetypes': ['tex','latex']  }

" UltiSnips settings
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<c-b>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"

if isdirectory("/usr/local/lib/python3.4/dist-packages/powerline/bindings/vim/")
    set rtp+=/usr/local/lib/python3.4/dist-packages/powerline/bindings/vim/
    set laststatus=2
    set showtabline=1
    set noshowmode
endif

" Mac directory is a little different -__-
if isdirectory("/usr/local/lib/python2.7/site-packages/powerline/bindings/vim/")
    set rtp+=/usr/local/lib/python2.7/site-packages/powerline/bindings/vim/
    set laststatus=2
    set showtabline=1
    set noshowmode
endif

" >>> Keymap commands <<<
"
" v goes into visual mode
" $ goes to end of line
" '_d cuts secection into black hole register
" 0 adds empty line
"
" >>>> SOURCES <<<<<
"
" Vim documentation: options:
" http://vimdoc.sourceforge.net/htmldoc/options.html#g:colors_name
"
" Syntax Highlighting
" http://www.sbf5.com/~cduan/technical/vi/vi-4.shtml#scheme
"
" Xterm 256color chart
" https://upload.wikimedia.org/wikipedia/en/1/15/Xterm_256color_chart.svg
