execute pathogen#infect()
syntax on
filetype plugin indent on

" Added settings
set number
set tabstop=8 "set for C programing"
set colorcolumn=110
colo pantheon_term
set timeoutlen=1000 ttimeoutlen=0 "Esc delay time"

" Unmap p in normal mode because of tmux p command
map p <Nop>
" Keymapping for window management
map = <C-W>+
map - <C-W>-
map , :vertical resize +5<CR>
map . :vertical resize -5<CR>

" Syntastic recommended settings
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1  
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

if isdirectory("/usr/local/lib/python3.4/dist-packages/powerline/bindings/vim/")
	set rtp+=/usr/local/lib/python3.4/dist-packages/powerline/bindings/vim/
	set laststatus=2
	set showtabline=1
       	set noshowmode
	set t_Co=256
endif

" >>>> SOURCES <<<<<
"
" Vim documentation: options:
" http://vimdoc.sourceforge.net/htmldoc/options.html#g:colors_name
"
" Syntax Highlighting
" http://www.sbf5.com/~cduan/technical/vi/vi-4.shtml#scheme
"
" Xterm 256color chart
" https://upload.wikimedia.org/wikipedia/en/1/15/Xterm_256color_chart.svg
