execute pathogen#infect()
syntax on
filetype plugin indent on

" Added settings
set number
set nowrap 				"Dont like wrapin in vim"
set colorcolumn=110 			"Colorcolumn length"
set timeoutlen=1000 ttimeoutlen=0 	"Esc delay time"
set incsearch 				"Show search matches while typing"
set wildmenu  				"Tab complete vim command menu"
set t_Co=256 				"Set to 16 to fix pantheon term colors in vim"
set backspace=indent,eol,start 		"Set backspace on everything in insert mode, for OS X"
colo marvin_martian

" Tab setting for diferent syntax
autocmd FileType vim,markdown,python,sh set tabstop=4
autocmd FileType c set tabstop=8

"Unmap p in normal mode because of tmux p command"
map p <Nop> 

"Delete line mapings
" v goes into visual mode
" $ goes to end of line
" '_d cuts secection into black hole register
" 0 adds empty line
nnoremap D v$"_d
nnoremap d v$"_d<Esc>O<Esc>

" vertical split key map"
nnoremap \ :vsp<CR>
imap <C-\> <Esc>:vsp<CR>

" Keymapping for window management
map = <C-W>+
map - <C-W>-
map , :vertical resize +5<CR>
map . :vertical resize -5<CR>

" Syntastic recommended settings
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1  
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0


if isdirectory("/usr/local/lib/python3.4/dist-packages/powerline/bindings/vim/")
	set rtp+=/usr/local/lib/python3.4/dist-packages/powerline/bindings/vim/
	set laststatus=2
	set showtabline=1
       	set noshowmode
endif

" Mac directory is a little different -__-
if isdirectory("/usr/local/lib/python2.7/site-packages/powerline/bindings/vim/")
	set rtp+=/usr/local/lib/python2.7/site-packages/powerline/bindings/vim/
	set laststatus=2
	set showtabline=1
       	set noshowmode
endif

" >>>> SOURCES <<<<<
"
" Vim documentation: options:
" http://vimdoc.sourceforge.net/htmldoc/options.html#g:colors_name
"
" Syntax Highlighting
" http://www.sbf5.com/~cduan/technical/vi/vi-4.shtml#scheme
"
" Xterm 256color chart
" https://upload.wikimedia.org/wikipedia/en/1/15/Xterm_256color_chart.svg
