---

- name: Set i3 config var for other tasks
  set_fact:
    i3_config_file: "{{ ansible_env.HOME }}/.config/i3/config"

- name: Configure i3 with generic/dotfile
  include_role:
    name: generic
    tasks_from: dotfile
  vars:
    package_redhat: "i3"
    package_debian: "i3"
    config_dir: "{{ ansible_env.HOME }}/.config/i3"
    config_src: "{{ playbook_dir }}/roles/i3/files/config"
    config_dest: "{{ i3_config_file }}"


- name: Setup brightness script root Script Permissions
  lineinfile:
    dest: /etc/sudoers
    state: present
    insertafter: EOF
    line: 'tristan ALL=(ALL) NOPASSWD: /usr/bin/tee /sys/class/backlight/intel_backlight/brightness'
  become: true
