---

- name: Install Polybar Dependencies
  yum:
          name: '{{ item }}'
  with_items:
    - g++
    - libX11-xcb.x86_64
    - libxcb.x86_64
    - libxcb-devel.x86_64
    - libxcb-doc.noarch
    - xcb-proto.noarch
    - xcb-util.x86_64
    - wireless-tools-devel
    - cmake
  become: True

- name: Clone Polybar From Git
  git:
    repo: 'https://github.com/jaagr/polybar.git'
    dest: "/tmp/polybar"

- name: Setup Polybar build
  file: 
    path: /tmp/polybar/build
    state: directory
  become: true

- name: Build and Install Polybar
  shell: "{{ item }}"
  args:
    chdir: /tmp/polybar/build
    # creates: bin/polybar  TODO: add this functionality (make install doesnt work with bin/polybar)
  with_items:
    - cmake ..
    - make -j$(nproc)
    - make install
  become: true
  ignore_errors: true

- name: Configure polybar with generic/dotfile
  include_role:
    name: generic
    tasks_from: dotfile
  vars:
    package_redhat: false
    package_debian: false
    config_dir: "{{ ansible_env.HOME }}/.config/polybar"
    config_src: "{{ playbook_dir }}/roles/polybar/files/config"
    config_dest: "{{ config_dir }}/config"

