---

- name: Install Polybar Dependencies
  yum:
    name:
      - g++
      - libX11-xcb.x86_64
      - libxcb.x86_64
      - libxcb-devel.x86_64
      - libxcb-doc.noarch
      - xcb-proto.noarch
      - xcb-util.x86_64
      - wireless-tools-devel
      - cmake
  become: True

- name: Clone Polybar From Git
  git:
    repo: 'https://github.com/jaagr/polybar.git'
    dest: "/tmp/polybar"

- name: Setup Polybar build
  file: 
    path: /tmp/polybar/build
    state: directory
  become: true

- name: Build Polybar
  shell: |-
    cmake \
    -DENABLE_ALSA:BOOL="OFF"        \
    -DENABLE_PULSEAUDIO:BOOL="ON"   \
    -DENABLE_I3:BOOL="ON"           \
    -DENABLE_MPD:BOOL="OFF"         \
    -DENABLE_NETWORK:BOOL="ON"      \
    -DENABLE_CURL:BOOL="ON"         \
    -DBUILD_IPC_MSG:BOOL="ON"       \
    .. && make -j$(nproc)
  args:
    chdir: /tmp/polybar/build
    creates: bin/polybar
  become: true

- name: Install Polybar
  shell:  make install
  args:
    chdir: /tmp/polybar/build
    creates: /usr/local/bin/polybar
  become: true

- name: Configure polybar with generic/dotfile
  include_role:
    name: generic
    tasks_from: dotfile
  vars:
    package_redhat: false
    package_debian: false
    config_dir: "{{ ansible_env.HOME }}/.config/polybar"
    config_src: "{{ playbook_dir }}/roles/polybar/files/config"
    config_dest: "{{ config_dir }}/config"

