---
# install cursor themes

- name: Add Capitaine Mouse theme Repo
  apt_repository:
    repo: ppa:dyatlov-igor/la-capitaine
    state: present
  become: true

- name: Install La Capitaine Packages
  apt:
          name: 'la-capitaine-cursor-theme'
  become: True

