---

 - set_fact:
         package: "polybar"
         config: ".config/polybar"
 
 - name: Install Polybar Dependencies
   yum:
           name: '{{ item }}'
   with_items:
     - libX11-xcb.x86_64
     - libxcb.x86_64
     - libxcb-devel.x86_64
     - libxcb-doc.noarch
     - xcb-proto.noarch
     - xcb-util.x86_64
     - cmake
   become: True

 - name: Clone Polybar From Git
   git:
     repo: 'https://github.com/jaagr/polybar.git'
     dest: "/tmp/polybar"
 
 - name: Setup Polybar build
   shell: "{{ item }}"
   args:
     chdir: "/tmp/polybar"
   with_items:
     - mkdir -p build
   become: true
   ignore_errors: true
 
 - name: Build and Install Polybar
   shell: "{{ item }}"
   args:
     chdir: "/tmp/polybar/build"
   with_items:
     - cmake ..
     - make -j$(nproc)
     - make install
   become: true
   ignore_errors: true
 
 - name: Checking Existing {{ config }}
   stat: path={{ ansible_env.HOME }}/{{ config }}
   register: file
 
 - name: Remove Old {{ config }}
   file: path={{ file.stat.path }} state=absent force=yes
   when: file.stat.exists == True
 
 - name: Linking {{ package }}
   command: "/bin/ln -fs {{ playbook_dir }}/roles/setup/files/{{ config }} {{ ansible_env.HOME }}/{{ config }}"
 
  
