---
# file: update.yml
# run basic update and upgrade


- name: Running Basic Apt Update
  apt:
          update_cache=yes
  become: True

- name: Running Basic Apt Upgrade
  apt:
          upgrade=dist
  become: True

