---
# run.yml
# run roles

- hosts: 127.0.0.1
  connection: local
  vars:
        theme_name: "glacier"
        terminal_id: "da53d9cf-e2f2-4b85-82bf-5cea26088d22"

        #####################################################
        ##################    COLORS    #####################
        #####################################################
        
        white: 'ffffff'
        black: '000000'
        terminal_white: 'C9C9C9'

        dark_gray: '2A2926'
        light_green: '5B5A52'
        ice_white: 'D1D6D2'
        glacier_blue: '95B4CB'
        glacier_black: '1C1C1C'
        
        base_dark: "{{ dark_gray }}"
        base_light: "{{ ice_white }}"

        #####################################################
        ################    i3 SETTINGs    ##################
        #####################################################
        
        i3_bar_bg: "{{ base_dark }}"
        i3_bar_fg: "{{ base_light }}"
        i3_active_bg: "{{ base_light }}"
        i3_active_fg: "{{ base_dark }}"
        i3_inactive_bg: "{{ base_light }}"
        i3_inactive_fg: "{{ base_dark }}"

        status_A_BG: "{{ base_light }}"
        status_A_FG: "{{ base_dark }}"
        status_B_BG: "{{ base_dark }}"
        status_B_FG: "{{ base_light }}"

        #####################################################
        ##############    DUNST  SETTINGs    ################
        #####################################################
        
        dunst_bg: "{{ base_light }}"
        dunst_fg: "{{ base_dark }}"
        
        #####################################################
        ###############    ROFI  SETTINGs    ################
        #####################################################

        rofi_bg: "{{ base_dark }}"
        rofi_fg: "{{ base_light }}"
        rofi_select: "{{ glacier_blue }}"

        #####################################################
        ###############    GTK3  SETTINGs    ################
        #####################################################

        gtk_window: "{{ black_green }}"
        gtk_menu_text: "{{ light_gray }}"

        #####################################################
        ############    TERMINAL  SETTINGs    ###############
        #####################################################
        
        terminal_bg: "{{ glacier_black }}"        
        terminal_fg: "{{ terminal_white }}"
        folder: "{{ glacier_blue }}"
        symlink: "{{ terminal_white }}"

        #                   0          1          2          3          4          5          6          7          8          9          10         11         12               13         14                15        
        terminal_colors: "['#282A2E', '#A54242', '#8C9440', '#DE935F', '#5F819D', '#85678F', '#5E8D87', '#707880', '#373B41', '#CC6666', '#B5BD68', '#F0C674', '#{{ folder }}', '#B294BB', '#{{ symlink }}', '#C5C8C6']"

  tasks:
        - name: Setup i3 Color
          lineinfile:
            dest: "{{ ansible_env.HOME }}/.i3/config"
            state: present
            regexp: 'set \${{ item.name }}.*'
            line: 'set ${{ item.name }} #{{ item.color }}'
          with_items: 
                - { name: "active_bg", color: "{{ i3_active_bg }}"}
                - { name: "active_fg", color: "{{ i3_active_fg }}"}
                - { name: "inactive_bg", color: "{{ i3_inactive_bg }}"}
                - { name: "inactive_fg", color: "{{ i3_inactive_fg }}"}
                - { name: "bar_bg", color: "{{ i3_bar_bg }}"}
                - { name: "bar_fg", color: "{{ i3_bar_fg }}"}
          register: config
          tags:
                - i3

        - name: Reload i3
          shell: i3-msg reload
          when: config.changed
          tags: 
                - i3

        - name: Setup Status Bar Color
          lineinfile:
            dest: "{{ ansible_env.HOME }}/.dotfiles/scripts/bar_status.py"
            state: present
            regexp: '{{ item.name }} =.*'
            line: '    {{ item.name }} = "{{ item.color }}"'
          with_items: 
                - { name: "a_bg", color: "{{ status_A_BG }}"}
                - { name: "a_fg", color: "{{ status_A_FG }}"}
                - { name: "b_bg", color: "{{ status_B_BG }}"}
                - { name: "b_fg", color: "{{ status_B_FG }}"}
          tags:
                - status


        - name: Colorize ROFI
          replace:
            dest: "{{ ansible_env.HOME }}/.config/rofi/config.rasi"
            regexp: '\ {4}{{ item.name }}:.*'
            replace: '    {{ item.name }}: #{{ item.color }};'
          with_items: 
                - { name: "background-color", color: "{{ rofi_bg }}"}
                - { name: "color", color: "{{ rofi_fg }}"}
                - { name: "text-color", color: "{{ rofi_select }}"}
          tags:
                - rofi
        
                
        - name: Setup Dunst Background Color
          replace:
            dest: "{{ ansible_env.HOME }}/.config/dunst/dunstrc"
            regexp: '{{ item.name }} =.*'
            replace: '{{ item.name }} = "#{{ item.color }}"'
          register: dunst
          with_items: 
                - { name: "background", color: "{{ dunst_bg }}"}
                - { name: "foreground", color: "{{ dunst_fg }}"}
                - { name: "frame_color", color: "{{ dunst_bg }}"}
          tags:
                - dunst
        
        - name: Restart Dunst
          command: killall dunst
          when: dunst.changed
          tags: 
                - dunst

        - name: Setup Gtk Color
          blockinfile:
            dest: "{{ ansible_env.HOME }}/.config/gtk-3.0/gtk.css"
            marker: "/* {mark} {{ item.name }} */"
            block: | 
                    {{ item.name }} { {{ item.attribute }}: #{{ item.color }}; }
          with_items:
                - { name: "GtkAccelLabel", attribute: "color",  color: "{{ gtk_menu_text }}" }
                - { name: "GtkMenuBar", attribute: "background-color", color: "{{ gtk_window }}"}

        - name: Config Terminal - Get Default Profile Id
          shell: "{{ playbook_dir }}/scripts/gterm_color.sh --palette \"{{ terminal_colors }}\" --background-color '#{{ terminal_bg }}' --foreground-color '#{{ terminal_fg }}' --name '{{ theme_name }}' --id 'da53d9cf-e2f2-4b85-82bf-5cea26088d21'"
          tags:
                - terminal



