---
# file cups_conf.yml
# configure cups with hp printer

- name: Clone HP Drivers From Git
  git:
    repo: 'https://github.com/twaugh/hplip.git'
    dest: "/tmp/hplp"

- name: Setup Printers
  command: "lpadmin -p {{ item.name }} -E -v {{ item.location }} -P /tmp/hplp/ppd/hpcups/{{ item.driver }}"
  with_items: "{{ printers }}"
  become: true
