---
# file: main.yml

- include: sym_link.yml
  tags: [all,vim,link]
- include: font.yml
  tags: [all,font,powerline]
- include: i3lock.yml
  tags: [all,lock]
- include: vim_plugins.yml
  tags: [all,vim]
- include: root_scripts.yml
  tags: [all,scripts]
- include: rc_local.yml
  tags: [all,rc]
- include: cups_conf.yml
  tags: [all,cups]
- include: terminal_config.yml
  tags: [all,terminal]
- include: network_timeout.yml
  tags: [all,net_timeout]
- include: gesture_setup.yml
  tags: [all,gesture]
