---
# file: sym_link.yml
# set sym links for home dir



- name: Checking Existing Dot Files
  stat: path={{ ansible_env.HOME }}/{{ item }}
  with_items: "{{ conf_files }}"
  register: file_stats

- name: Checking Existing Dot Folders
  stat: path={{ ansible_env.HOME }}/{{ item }}
  with_items: "{{ conf_folders }}"
  register: folder_stats

- name: Remove Old Dot Files
  file: path={{ item.stat.path }} state=absent force=yes
  when: (item.stat.exists == True) and (item.stat.islnk == False)
  with_items: "{{ file_stats.results }}"

- name: Remove Old Dot Folders
  file: path={{ item.stat.path }} state=absent force=yes
  when: item.stat.exists == True
  with_items: "{{ folder_stats.results }}"

- name: Setting HOME Dot Files
  file: src={{ ansible_env.HOME }}/.dotfiles/{{ item }} dest={{ ansible_env.HOME }}/{{ item }} state=link
  with_items: "{{ conf_files }}"

- name: Setting HOME Dot Folders
  command: "/bin/ln -fs {{ ansible_env.HOME }}/.dotfiles/{{ item }} {{ ansible_env.HOME }}/{{ item }}"
  with_items: "{{ conf_folders }}"
