---
# run.yml
# run roles

- hosts: local
  connection: local
  vars:
          apps:
              - ssh
              - git
              - vim
              - smbclient
              - wpasupplicant
              - xinit
              - i3 
              - tmux
              - compton
              - conky
              - thunar
              - build-essential
              - python3-pip
              - feh
              - acpi
              - pulseaudio-utils
              - fonts-font-awesome
              - pantheon-terminal
              - dconf-editor
              - numix-gtk-theme
              - tree
              - chromium-browser
              - papirus-icon-theme
              - imagemagick
                # needed for i3lock build
              - pkg-config
              - libcairo2-dev
              - libxcb-dpms0-dev
              - libxcb-xinerama0-dev
              - libxcb-image0-dev
              - libxcb-xkb-dev
              - libxkbcommon-dev
              - libxkbcommon-x11-dev
              - libxcb-util-dev
              - libpam0g-dev
              - libev-dev
  roles:
          - i3laptop

